"""Ajout table mails_a_envoyer

Revision ID: 074648137ace
Revises: 8f9f9d274dc6
Create Date: 2026-09-18 11:47:38.632958

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '074648137ace'
down_revision: Union[str, Sequence[str], None] = '8f9f9d274dc6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('mails_a_envoyer',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('destinataire', sa.String(length=255), nullable=False),
    sa.Column('sujet', sa.String(length=255), nullable=False),
    sa.Column('corps', sa.Text(), nullable=False),
    sa.Column('statut', sa.String(length=20), nullable=False),
    sa.Column('message_erreur', sa.Text(), nullable=True),
    sa.Column('date_creation', sa.DateTime(), nullable=False),
    sa.Column('date_envoi', sa.DateTime(), nullable=True),
    sa.Column('demande_id', sa.Integer(), nullable=True),
    sa.Column('type_mail', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['demande_id'], ['demandes_rh.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('mails_a_envoyer')
    # ### end Alembic commands ###
