"""Ajout email_pro dans employes

Revision ID: 0d4c4bafd1d8
Revises: 074648137ace
Create Date: 2026-09-18 12:16:23.543872

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0d4c4bafd1d8'
down_revision: Union[str, Sequence[str], None] = '074648137ace'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('employes', sa.Column('email_pro', sa.String(length=150), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('employes', 'email_pro')
    # ### end Alembic commands ###
