"""creation tables initiales

Revision ID: 2d4582309101
Revises: 
Create Date: 2026-09-09 09:41:06.937046

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2d4582309101'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('agences',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nom', sa.String(length=150), nullable=False),
    sa.Column('ville', sa.String(length=100), nullable=True),
    sa.Column('region', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nom')
    )
    op.create_table('departements',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nom', sa.String(length=150), nullable=False),
    sa.Column('code', sa.String(length=20), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code'),
    sa.UniqueConstraint('nom')
    )
    op.create_table('grades',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('libelle', sa.String(length=100), nullable=False),
    sa.Column('niveau_hierarchique', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('libelle')
    )
    op.create_table('postes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('intitule', sa.String(length=200), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('intitule')
    )
    op.create_table('types_absence',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=10), nullable=False),
    sa.Column('libelle', sa.String(length=150), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_table('types_demande',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('libelle', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('libelle')
    )
    op.create_table('employes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('matricule', sa.String(length=20), nullable=True),
    sa.Column('nom', sa.String(length=100), nullable=False),
    sa.Column('prenom', sa.String(length=100), nullable=False),
    sa.Column('genre', sa.String(length=1), nullable=True),
    sa.Column('date_embauche', sa.Date(), nullable=False),
    sa.Column('telephone_pro', sa.String(length=30), nullable=True),
    sa.Column('telephone_perso', sa.String(length=30), nullable=True),
    sa.Column('email_perso', sa.String(length=150), nullable=True),
    sa.Column('statut', sa.String(length=20), nullable=True),
    sa.Column('departement_id', sa.Integer(), nullable=False),
    sa.Column('agence_id', sa.Integer(), nullable=True),
    sa.Column('poste_id', sa.Integer(), nullable=False),
    sa.Column('grade_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.CheckConstraint("genre IN ('H','F')", name='ck_employe_genre'),
    sa.ForeignKeyConstraint(['agence_id'], ['agences.id'], ),
    sa.ForeignKeyConstraint(['departement_id'], ['departements.id'], ),
    sa.ForeignKeyConstraint(['grade_id'], ['grades.id'], ),
    sa.ForeignKeyConstraint(['poste_id'], ['postes.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('matricule')
    )
    op.create_table('absences',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('employe_id', sa.Integer(), nullable=False),
    sa.Column('type_absence_id', sa.Integer(), nullable=False),
    sa.Column('date_debut', sa.Date(), nullable=False),
    sa.Column('date_fin', sa.Date(), nullable=False),
    sa.Column('motif', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['employe_id'], ['employes.id'], ),
    sa.ForeignKeyConstraint(['type_absence_id'], ['types_absence.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('affectations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('employe_id', sa.Integer(), nullable=False),
    sa.Column('departement_id', sa.Integer(), nullable=True),
    sa.Column('agence_id', sa.Integer(), nullable=True),
    sa.Column('poste_id', sa.Integer(), nullable=False),
    sa.Column('grade_id', sa.Integer(), nullable=False),
    sa.Column('date_debut', sa.Date(), nullable=False),
    sa.Column('date_fin', sa.Date(), nullable=True),
    sa.Column('type_mouvement', sa.String(length=30), nullable=True),
    sa.Column('motif', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['agence_id'], ['agences.id'], ),
    sa.ForeignKeyConstraint(['departement_id'], ['departements.id'], ),
    sa.ForeignKeyConstraint(['employe_id'], ['employes.id'], ),
    sa.ForeignKeyConstraint(['grade_id'], ['grades.id'], ),
    sa.ForeignKeyConstraint(['poste_id'], ['postes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('departs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('employe_id', sa.Integer(), nullable=False),
    sa.Column('date_depart', sa.Date(), nullable=False),
    sa.Column('motif', sa.Text(), nullable=True),
    sa.Column('type_depart', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['employe_id'], ['employes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('solde_conges',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('employe_id', sa.Integer(), nullable=False),
    sa.Column('annee', sa.Integer(), nullable=False),
    sa.Column('jours_alloues', sa.Numeric(precision=5, scale=1), nullable=True),
    sa.Column('jours_pris', sa.Numeric(precision=5, scale=1), nullable=True),
    sa.Column('jours_restants', sa.Numeric(precision=5, scale=1), nullable=True),
    sa.ForeignKeyConstraint(['employe_id'], ['employes.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('employe_id', 'annee', name='uq_solde_employe_annee')
    )
    op.create_table('utilisateurs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nom', sa.String(length=150), nullable=False),
    sa.Column('email', sa.String(length=150), nullable=False),
    sa.Column('mot_de_passe_hash', sa.String(length=255), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=True),
    sa.Column('employe_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['employe_id'], ['employes.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('demandes_rh',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('type_demande_id', sa.Integer(), nullable=False),
    sa.Column('employe_concerne_id', sa.Integer(), nullable=True),
    sa.Column('demandeur_id', sa.Integer(), nullable=False),
    sa.Column('date_demande', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('statut', sa.String(length=20), nullable=True),
    sa.Column('valide_par_id', sa.Integer(), nullable=True),
    sa.Column('date_validation', sa.DateTime(), nullable=True),
    sa.Column('commentaire', sa.Text(), nullable=True),
    sa.Column('donnees_specifiques', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['demandeur_id'], ['utilisateurs.id'], ),
    sa.ForeignKeyConstraint(['employe_concerne_id'], ['employes.id'], ),
    sa.ForeignKeyConstraint(['type_demande_id'], ['types_demande.id'], ),
    sa.ForeignKeyConstraint(['valide_par_id'], ['utilisateurs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('demandes_rh')
    op.drop_table('utilisateurs')
    op.drop_table('solde_conges')
    op.drop_table('departs')
    op.drop_table('affectations')
    op.drop_table('absences')
    op.drop_table('employes')
    op.drop_table('types_demande')
    op.drop_table('types_absence')
    op.drop_table('postes')
    op.drop_table('grades')
    op.drop_table('departements')
    op.drop_table('agences')
    # ### end Alembic commands ###
