"""Types absence : duree standard

Revision ID: 7d6c5b694cdd
Revises: e1984eda5c6f
Create Date: 2026-09-15 15:43:26.245960

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7d6c5b694cdd'
down_revision: Union[str, Sequence[str], None] = 'e1984eda5c6f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('types_absence', sa.Column('duree_standard_jours', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('types_absence', 'duree_standard_jours')
    # ### end Alembic commands ###
