"""Workflow N+1 : n_plus_1_id, avis, periodes, suppleant

Revision ID: 8f9f9d274dc6
Revises: cff86fab8924
Create Date: 2026-09-17 11:19:58.415433

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '8f9f9d274dc6'
down_revision: Union[str, Sequence[str], None] = 'cff86fab8924'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('demandes_rh', sa.Column('suppleant_id', sa.Integer(), nullable=True))
    op.add_column('demandes_rh', sa.Column('avis_n_plus_1', sa.String(length=20), nullable=True))
    op.add_column('demandes_rh', sa.Column('commentaire_n_plus_1', sa.Text(), nullable=True))
    op.add_column('demandes_rh', sa.Column('date_avis_n_plus_1', sa.DateTime(), nullable=True))
    op.add_column('demandes_rh', sa.Column('periode_sollicitee_debut', sa.Date(), nullable=True))
    op.add_column('demandes_rh', sa.Column('periode_sollicitee_fin', sa.Date(), nullable=True))
    op.add_column('demandes_rh', sa.Column('periode_accordee_debut', sa.Date(), nullable=True))
    op.add_column('demandes_rh', sa.Column('periode_accordee_fin', sa.Date(), nullable=True))
    op.alter_column('demandes_rh', 'statut',
               existing_type=mysql.VARCHAR(length=20),
               type_=sa.String(length=30),
               existing_nullable=True)
    op.create_foreign_key('fk_demandes_rh_suppleant', 'demandes_rh', 'employes', ['suppleant_id'], ['id'])
    op.add_column('employes', sa.Column('n_plus_1_id', sa.Integer(), nullable=True))
    op.create_foreign_key('fk_employes_n_plus_1', 'employes', 'employes', ['n_plus_1_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_employes_n_plus_1', 'employes', type_='foreignkey')
    op.drop_column('employes', 'n_plus_1_id')
    op.drop_constraint('fk_demandes_rh_suppleant', 'demandes_rh', type_='foreignkey')
    op.alter_column('demandes_rh', 'statut',
               existing_type=sa.String(length=30),
               type_=mysql.VARCHAR(length=20),
               existing_nullable=True)
    op.drop_column('demandes_rh', 'periode_accordee_fin')
    op.drop_column('demandes_rh', 'periode_accordee_debut')
    op.drop_column('demandes_rh', 'periode_sollicitee_fin')
    op.drop_column('demandes_rh', 'periode_sollicitee_debut')
    op.drop_column('demandes_rh', 'date_avis_n_plus_1')
    op.drop_column('demandes_rh', 'commentaire_n_plus_1')
    op.drop_column('demandes_rh', 'avis_n_plus_1')
    op.drop_column('demandes_rh', 'suppleant_id')
    # ### end Alembic commands ###
