"""ajout date_naissance photo cni plan_localisation

Revision ID: 91220ca8d70c
Revises: 2d4582309101
Create Date: 2026-09-13 22:00:45.611189

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '91220ca8d70c'
down_revision: Union[str, Sequence[str], None] = '2d4582309101'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('employes', sa.Column('date_naissance', sa.Date(), nullable=True))
    op.add_column('employes', sa.Column('photo_path', sa.String(length=255), nullable=True))
    op.add_column('employes', sa.Column('cni_path', sa.String(length=255), nullable=True))
    op.add_column('employes', sa.Column('plan_localisation_path', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('employes', 'plan_localisation_path')
    op.drop_column('employes', 'cni_path')
    op.drop_column('employes', 'photo_path')
    op.drop_column('employes', 'date_naissance')
    # ### end Alembic commands ###
