"""Ajout champs employe + table sanctions

Revision ID: c6354e821ff6
Revises: 91220ca8d70c
Create Date: 2026-09-15 09:43:37.445096

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c6354e821ff6'
down_revision: Union[str, Sequence[str], None] = '91220ca8d70c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sanctions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('employe_id', sa.Integer(), nullable=False),
    sa.Column('type_sanction', sa.String(length=50), nullable=False),
    sa.Column('motif', sa.Text(), nullable=True),
    sa.Column('date_sanction', sa.Date(), nullable=False),
    sa.Column('duree', sa.String(length=30), nullable=True),
    sa.Column('commentaire', sa.Text(), nullable=True),
    sa.Column('enregistre_par', sa.String(length=100), nullable=True),
    sa.Column('date_enregistrement', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['employe_id'], ['employes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sanctions_id'), 'sanctions', ['id'], unique=False)
    op.add_column('employes', sa.Column('statut_matrimonial', sa.String(length=30), nullable=True))
    op.add_column('employes', sa.Column('nombre_enfants', sa.Integer(), nullable=True))
    op.add_column('employes', sa.Column('contact_urgence_nom', sa.String(length=100), nullable=True))
    op.add_column('employes', sa.Column('contact_urgence_tel', sa.String(length=30), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('employes', 'contact_urgence_tel')
    op.drop_column('employes', 'contact_urgence_nom')
    op.drop_column('employes', 'nombre_enfants')
    op.drop_column('employes', 'statut_matrimonial')
    op.drop_index(op.f('ix_sanctions_id'), table_name='sanctions')
    op.drop_table('sanctions')
    # ### end Alembic commands ###
