"""Absences : champs justifiee et justificatif

Revision ID: ccba44b5e92e
Revises: c6354e821ff6
Create Date: 2026-09-15 13:28:51.741540

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ccba44b5e92e'
down_revision: Union[str, Sequence[str], None] = 'c6354e821ff6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('absences', sa.Column('justifiee', sa.Boolean(), nullable=False, server_default=sa.false()))
    op.add_column('absences', sa.Column('justificatif_path', sa.String(length=255), nullable=True))
    op.add_column('absences', sa.Column('enregistre_par', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('absences', 'enregistre_par')
    op.drop_column('absences', 'justificatif_path')
    op.drop_column('absences', 'justifiee')
    # ### end Alembic commands ###
