"""Absences : date enregistrement

Revision ID: cff86fab8924
Revises: fc3e7a0627e4
Create Date: 2026-09-16 11:11:09.624711

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cff86fab8924'
down_revision: Union[str, Sequence[str], None] = 'fc3e7a0627e4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('absences', sa.Column('date_enregistrement', sa.DateTime(), nullable=False, server_default=sa.func.now()))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('absences', 'date_enregistrement')
    # ### end Alembic commands ###
