"""Types absence : categorie, plafond, deductible + jours_deduits

Revision ID: e1984eda5c6f
Revises: ccba44b5e92e
Create Date: 2026-09-15 14:50:25.435011

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'e1984eda5c6f'
down_revision: Union[str, Sequence[str], None] = 'ccba44b5e92e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('absences', sa.Column('jours_deduits_conges', sa.Numeric(precision=5, scale=1), nullable=True))
    op.add_column('types_absence', sa.Column('categorie', sa.String(length=20), nullable=False, server_default='Absence'))
    op.add_column('types_absence', sa.Column('deductible_conge', sa.Boolean(), nullable=True, server_default=sa.false()))
    op.add_column('types_absence', sa.Column('genre_requis', sa.String(length=1), nullable=True))
    op.add_column('types_absence', sa.Column('plafond_jours', sa.Integer(), nullable=True))
    op.alter_column('types_absence', 'code',
               existing_type=mysql.VARCHAR(length=10),
               type_=sa.String(length=20),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('types_absence', 'code',
               existing_type=sa.String(length=20),
               type_=mysql.VARCHAR(length=10),
               existing_nullable=False)
    op.drop_column('types_absence', 'deductible_conge')
    op.drop_column('types_absence', 'plafond_jours')
    op.drop_column('types_absence', 'genre_requis')
    op.drop_column('types_absence', 'categorie')
    op.drop_column('absences', 'jours_deduits_conges')
    # ### end Alembic commands ###
