"""Absences : champ archivee

Revision ID: fc3e7a0627e4
Revises: 7d6c5b694cdd
Create Date: 2026-09-16 08:37:52.219923

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fc3e7a0627e4'
down_revision: Union[str, Sequence[str], None] = '7d6c5b694cdd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('absences', sa.Column('archivee', sa.Boolean(), nullable=False, server_default=sa.false()))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('absences', 'archivee')
    # ### end Alembic commands ###
